# Generated by Django 5.2.9 on 2025-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("vendor", "Vendor")],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
