# Generated by Django 5.2.9 on 2026-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="x_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="x_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
