# Generated by Django 5.2.9 on 2026-01-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_x_access_token_user_x_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="x_access_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="x_refresh_token",
        ),
    ]
